apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fulfil-pod
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fulfil-pod
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
